import { useState } from "react";
import Navbar from "./Components/Navbar";
import CreateForm from './Components/CreateForm'
import axios from 'axios'
import Head from 'next/head'
import styles from '../styles/Home.module.css'


// Pagina de creacion de usuarios
// La primera seccion esta modificada para que los campos por defecto muestren la informacion almacenada de los usuarios en caso de actualizar la info
export default function createUser() {
  const [fechaRegistro, cambiarFechaRegistro] = useState(new Date());
  const [fechaNacimiento, cambiarFechaNacimiento] = useState(new Date());
  function getEdad(dateString) {
    let hoy = new Date();
    let edad = hoy.getFullYear() - fechaNacimiento.getFullYear()
    let diferenciaMeses = hoy.getMonth() - fechaNacimiento.getMonth();
    if (diferenciaMeses < 0 || (diferenciaMeses === 0 && hoy.getDate() < fechaNacimiento.getDate())){
      edad--
    }
    return edad
  }
  const [formCheck, setFormCheck] = useState({q0: false});
  const [form, setValues] = useState({
    history: {},

    //Esta forma de valores por defecto no muestra los valores guardados de usuarios

    // registrodate: "",
    // // name: "",
    // email: "",
    // surname: "",
    // passportCI: "",
    // age: 0,
    // civilState: "",
    // citizenship: "",
    // profession: "",
    // cellphone: "",
    // address: "",
    // address2: "",
  });
  const handleSubmit = (event) => {
    event.preventDefault();
    console.log(form);
    axios.post(`https://prog-proyect.vercel.app/api/users`, form)
        .then(response => {
          console.log(response)
          window.location.replace("/listUsers")
        })
        .catch((error) => {
            console.log(error)
        })
  };
  const handleInput = (event) => {
    setValues({
      ...form,
      history: {
        ...formCheck,
      },
      [event.target.name]: event.target.value,
    });
  };
  const handleBlur = (event) => {
    setValues({
      ...form,
      age: getEdad(fechaNacimiento),
      registryDate: fechaRegistro,
      birthDate: fechaNacimiento,
    })
  }
  const handleChange = (event) => {
    setFormCheck({
      ...formCheck,
      [event.target.name]: event.target.checked,
    });
  };
  const handleClick = (event) => {
    setValues({
      ...form,
      history: {
        ...formCheck,
      },
    });
  };
  return (
    <div>
      <Navbar></Navbar>
      <Head>
        {/* Pestaña  */}
        <title>Crear usuario</title>
        <meta name="description" content="Generated by create next app p" />
        <link rel="icon" href="/logo.png" />
      </Head>

      {/* Titulo con estilo global */}
      <div className="mb-4">
      <h1 className={styles.title}>Crear <font color='blue'>usuario</font></h1>
      </div>

      {/* Componente con los campos y su formato */}
      <CreateForm
        form={form}
        handleSubmit={handleSubmit}
        handleInput={handleInput}
        handleChange={handleChange}
        handleClick={handleClick}
        fechaRegistro={fechaRegistro}
        cambiarFechaRegistro={cambiarFechaRegistro}
        fechaNacimiento={fechaNacimiento}
        cambiarFechaNacimiento={cambiarFechaNacimiento}
        handleBlur={handleBlur}
      ></CreateForm>
    </div>
  );
}
