import { useState } from "react";
import Navbar from "./Components/Navbar";
import CreateForm from './Components/CreateForm'
import axios from 'axios'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
export default function createUser() {
  const [form, setValues] = useState({
    registrodate: "",
    name: "",
    email: "",
    surname: "",
    passportCI: "",
    age: 0,
    civilState: "",
    citizenship: "",
    profession: "",
    cellphone: "",
    address: "",
    address2: "",
  });
  const handleSubmit = (event) => {
    axios.post(`https://prog-proyect.vercel.app/api/users`, {
        registrodate: form.registrodate,
        name: form.name,
        email: form.email,
        surname: form.surname,
        passportCI: form.passportCI,
        age: form.age,
        civilState: form.civilState,
        citizenship: form.citizenship,
        profession: form.profession,
        cellphone: form.cellphone,
        address: form.address,
        address2: form.address2,
    })
        .then(response => {
          console.log(response)
          window.location.replace("/listUsers")
        })
        .catch((error) => {
            console.log(error)
        })
    event.preventDefault();
  }
  const handleInput = (event) => {
    setValues({
      ...form,
      [event.target.name]: event.target.value,
    });
  };
  return (
    <div >
      
      <Navbar></Navbar>
      <Head>
        <title>Crear usuario</title>
        <meta name="description" content="Generated by create next app p" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <h1 className={styles.title}>Crear usuario</h1>
      <CreateForm form={form} handleSubmit={handleSubmit} handleInput={handleInput}></CreateForm>
    </div>
  );
}
