import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from './Components/Navbar'



export default function Home() {
  return (
    <div className={styles.container}>
      <Navbar></Navbar>
      <Head>
        <title>DentaList</title>
        <meta name="description" content="Generated by create next app p" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido a Denta<font color='blue'>List</font>
        </h1>

        <p className={styles.description}>
          Sistema de gestión clínica dental
        </p>

        <div className={styles.grid}>
          <a href='/createUser' className={styles.card}>
            <h2>Crear usuario &rarr;</h2>
            <p>Añade un paciente nuevo a la base de datos. Se incluyen datos personales y su historial clínico.</p>
          </a>

          <a href="/listUsers" className={styles.card}>
            <h2>Pacientes &rarr;</h2>
            <p>Revisa los datos personales e historial clínico de pacientes registrados.</p>
          </a>

          <a href="/createAppointment" className={styles.card} >
            <h2>Agendar cita &rarr;</h2>
            <p>Agenda una cita para un paciente nuevo o uno registrado. También envia recordatorio un dia antes de la cita.</p>
          </a>

          <a
            href="/appointments"
            className={styles.card}
          >
            <h2>Citas &rarr;</h2>
            <p>
              Revisa o actualiza citas pasadas y pendientes. Registra pacientes con citas pero sin historial clínico. Genera facturas y lleva un registro del pago.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a target="_blank" rel="noopener noreferrer">
          Proyecto de programación 2 
        </a>
      </footer>
    </div>
  )
}
